######################################################################
# Automatically generated by qmake (3.0) ?? ???. 29 15:42:03 2019
######################################################################

TEMPLATE = app
TARGET = MyServerXML
INCLUDEPATH += .

# Input
HEADERS += myserverxml.h
SOURCES += main.cpp myserverxml.cpp

QT += widgets\
      core\
      network\
      xml
CONFIG +=c++11

